// <auto-generated />
using System;
using BookingManagement.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookingManagement.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    [Migration("20220516093650_InitialCreateBookingDB")]
    partial class InitialCreateBookingDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.16")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Common.Models.FlightBookingDetails", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("seatNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("flightDetail");
                });

            modelBuilder.Entity("Common.Models.Person", b =>
                {
                    b.Property<int>("peopleId")
                        .HasColumnType("int")
                        .HasColumnName("PeopleId");

                    b.Property<int?>("Age")
                        .HasColumnType("int");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserBookingTblid")
                        .HasColumnType("int");

                    b.HasKey("peopleId");

                    b.HasIndex("UserBookingTblid");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Common.Models.UserBookingTbl", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlightNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Meal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NoOfSeatBook")
                        .HasColumnType("int");

                    b.Property<string>("Pnr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SeatNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("personId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("bookingTbls");
                });

            modelBuilder.Entity("Common.Models.Person", b =>
                {
                    b.HasOne("Common.Models.UserBookingTbl", null)
                        .WithMany("userDetail")
                        .HasForeignKey("UserBookingTblid");
                });

            modelBuilder.Entity("Common.Models.UserBookingTbl", b =>
                {
                    b.Navigation("userDetail");
                });
#pragma warning restore 612, 618
        }
    }
}
